// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Search")]
[assembly: AssemblyDescriptionAttribute("A client SDK for Microsoft Azure Search.")]
[assembly: AssemblyProductAttribute("Red Dog")]
[assembly: AssemblyVersionAttribute("0.3.0.0")]
[assembly: AssemblyFileVersionAttribute("0.3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.0.0";
    }
}
